import type { NextRequest } from 'next/server'
import { NextResponse } from 'next/server'

import { getPublicOrigin } from '@/lib/public-request-url'
import { getSiteConfigMemoryFirst } from '@/lib/site-config-cache'

export const dynamic = 'force-dynamic'
export const revalidate = 0

export async function GET(request: NextRequest) {
  const cfg = await getSiteConfigMemoryFirst()
  const origin = getPublicOrigin(request)
  const preferredToolMode =
    String(cfg?.aiToolMode ?? '').trim().toLowerCase() === 'mcp' ? 'mcp' : 'skills'
  const llmBaseUrl = `${origin}/api/llm`
  const directUrl = `${llmBaseUrl}/direct`
  const settingsUrl = `${llmBaseUrl}/settings`
  const appsExportUrl = `${llmBaseUrl}/activity/apps-export`
  const legacyMcpUrl = `${llmBaseUrl}/mcp`
  const legacyMcpApiKeyVerifyUrl = `${llmBaseUrl}/mcp/apikey`

  const lines: string[] = []

  lines.push('---')
  lines.push('name: waken-wa-agent-skills')
  lines.push('description: >-')
  lines.push('  Agent execution protocol for Waken site debugging and configuration changes.')
  lines.push('  Read this document first, then follow the decision rules exactly.')
  lines.push('metadata:')
  lines.push('  author: waken-wa')
  lines.push('  version: 3.1.0')
  lines.push('  category: development')
  lines.push('  tags: [agent-protocol, llm-api, configuration]')
  lines.push('---')
  lines.push('')
  lines.push('# Waken AI Debugging Protocol')
  lines.push('')
  lines.push('This document is written for AI clients. Treat it as an execution protocol, not as general prose.')
  lines.push('')
  lines.push('## Absolute Base URL')
  lines.push('')
  lines.push('Use this exact origin for all runtime calls:')
  lines.push('')
  lines.push('```')
  lines.push(origin)
  lines.push('```')
  lines.push('')
  lines.push('## Preferred Tool Mode')
  lines.push('')
  lines.push(`User-selected preferred tool mode: **${preferredToolMode}**`)
  lines.push('')
  lines.push('Important:')
  lines.push('- This is a preference, not a guarantee that the mode is usable right now')
  lines.push('- You must still run runtime detection before performing actions')
  lines.push('')
  lines.push('## Canonical Endpoints')
  lines.push('')
  lines.push('| Endpoint | Use |')
  lines.push('|----------|-----|')
  lines.push(`| \`GET ${directUrl}\` | Required first call. Runtime detection and next-step guide |`)
  lines.push(`| \`GET ${llmBaseUrl}/md\` | This document |`)
  lines.push(`| \`GET ${settingsUrl}\` | Read site settings |`)
  lines.push(`| \`PATCH ${settingsUrl}\` | Update site settings |`)
  lines.push(`| \`GET ${appsExportUrl}\` | Export used activity apps |`)
  lines.push(`| \`${legacyMcpUrl}\` | Legacy MCP fallback endpoint |`)
  lines.push(`| \`POST ${legacyMcpApiKeyVerifyUrl}\` | Verify dedicated MCP API key |`)
  lines.push('')
  lines.push('Rule:')
  lines.push('- For HTTP execution, use only `/api/llm/*` endpoints')
  lines.push('- Do not use old admin endpoints for AI execution')
  lines.push('')
  lines.push('## Required Decision Order')
  lines.push('')
  lines.push('Follow these steps in order:')
  lines.push('')
  lines.push(`1. Call \`GET ${directUrl}\``)
  lines.push('2. Read `preferredToolMode` from the response')
  lines.push('3. Read `data.detectedMode` if `success === true`')
  lines.push('4. If `success !== true`, stop and surface the server guide to the user')
  lines.push('5. If preferred mode is `skills`, use Skills flow first')
  lines.push('6. If preferred mode is `mcp`, use MCP flow first')
  lines.push('7. Only use fallback when the preferred mode is unavailable and the server indicates the fallback is enabled')
  lines.push('')
  lines.push('## Runtime Rules')
  lines.push('')
  lines.push('Hard rules:')
  lines.push('- Treat Skills and MCP as mutually exclusive modes')
  lines.push('- `aiToolMode=skills` means HTTP Skills is the active protocol and MCP must be treated as off')
  lines.push('- `aiToolMode=mcp` means MCP is the active protocol and Skills HTTP endpoints must be treated as off')
  lines.push('- Never assume auth mode from memory')
  lines.push('- Never assume MCP is enabled just because a URL exists')
  lines.push('- Never send a full settings object when changing one or two fields')
  lines.push('- Never PATCH restricted fields')
  lines.push('- If any required credential is missing, stop and ask the user')
  lines.push('')
  lines.push('## Credential Priority')
  lines.push('')
  lines.push('Use credentials in this order:')
  lines.push('')
  lines.push('1. Use the current request origin shown in `Absolute Base URL`')
  lines.push('2. Call `direct` and read the server-returned header template')
  lines.push('3. Use only credentials required by the current mode')
  lines.push('4. If a required field is missing, stop immediately')
  lines.push('')
  lines.push('## Skills Flow')
  lines.push('')
  lines.push('### Required Headers')
  lines.push('')
  lines.push('```')
  lines.push('LLM-Skills-Mode: oauth | apikey')
  lines.push('LLM-Skills-Token: YOUR_TOKEN')
  lines.push('LLM-Skills-AI: YOUR_UNIQUE_AI_ID   # required in OAuth mode')
  lines.push('LLM-Skills-Scope: feature | theme | content')
  lines.push('LLM-Skills-Request-Id: ANY_REQUEST_ID')
  lines.push('```')
  lines.push('')
  lines.push('### OAuth Procedure')
  lines.push('')
  lines.push(`1. Call \`GET ${directUrl}?mode=oauth&ai=YOUR_UNIQUE_AI_ID\``)
  lines.push('2. Read the short-lived authorize link from the response')
  lines.push('3. Ask the user to open and confirm that authorize link')
  lines.push('4. After confirmation, retry using the newly issued token')
  lines.push('5. Use `/api/llm/settings` or `/api/llm/activity/apps-export` only after auth succeeds')
  lines.push('')
  lines.push('### API Key Procedure')
  lines.push('')
  lines.push(`1. Call \`GET ${directUrl}?mode=apikey\``)
  lines.push('2. Read the returned headers template')
  lines.push('3. Use `/api/llm/settings` or `/api/llm/activity/apps-export` only after auth succeeds')
  lines.push('')
  lines.push('## MCP Flow')
  lines.push('')
  lines.push('Use MCP only if all conditions are true:')
  lines.push('- The preferred mode is `mcp`, or Skills cannot be used')
  lines.push('- The server indicates MCP is enabled')
  lines.push('- A dedicated MCP API key is available')
  lines.push('')
  lines.push('### MCP Authentication')
  lines.push('')
  lines.push('```')
  lines.push('Authorization: Bearer YOUR_LEGACY_MCP_APIKEY')
  lines.push('```')
  lines.push('')
  lines.push('### MCP Verification')
  lines.push('')
  lines.push('```')
  lines.push(`POST ${legacyMcpApiKeyVerifyUrl}`)
  lines.push('Authorization: Bearer YOUR_LEGACY_MCP_APIKEY')
  lines.push('```')
  lines.push('')
  lines.push('### MCP Client Example')
  lines.push('')
  lines.push('```json')
  lines.push('{')
  lines.push('  "waken-wa-legacy-mcp": {')
  lines.push(`    "url": "${legacyMcpUrl}",`)
  lines.push('    "headers": {')
  lines.push('      "Authorization": "Bearer YOUR_LEGACY_MCP_APIKEY"')
  lines.push('    }')
  lines.push('  }')
  lines.push('}')
  lines.push('```')
  lines.push('')
  lines.push('### MCP Tools')
  lines.push('')
  lines.push('Meaning:')
  lines.push('- MCP is the tool-style transport for clients that can connect to an MCP server')
  lines.push('- Skills is the plain HTTP API-style transport for clients that cannot use MCP tools')
  lines.push('- Both transports operate on the same site configuration domain, but only one mode is active at a time')
  lines.push('- If the server is currently in `mcp` mode, prefer MCP and do not keep retrying Skills HTTP endpoints')
  lines.push('- If the server is currently in `skills` mode, prefer Skills HTTP and treat MCP as disabled even if an old MCP key still exists')
  lines.push('')
  lines.push('- `get_site_settings`')
  lines.push('- `update_site_settings`')
  lines.push('- `export_activity_apps`')
  lines.push('')
  lines.push('## Read and Write Operations')
  lines.push('')
  lines.push('### Read Current Settings')
  lines.push('')
  lines.push('```')
  lines.push(`GET ${settingsUrl}`)
  lines.push('```')
  lines.push('')
  lines.push('### Update Settings')
  lines.push('')
  lines.push('```')
  lines.push(`PATCH ${settingsUrl}`)
  lines.push('Content-Type: application/json')
  lines.push('')
  lines.push('{ "fieldName": "newValue" }')
  lines.push('```')
  lines.push('')
  lines.push('Rule:')
  lines.push('- Send only fields that must change')
  lines.push('- Do not send the whole settings object')
  lines.push('')
  lines.push('### Export Used Apps')
  lines.push('')
  lines.push('```')
  lines.push(`GET ${appsExportUrl}`)
  lines.push('```')
  lines.push('')
  lines.push('## Restricted Fields')
  lines.push('')
  lines.push('Do not modify these fields through the dedicated LLM HTTP API:')
  lines.push('')
  lines.push('- `useNoSqlAsCacheRedis`')
  lines.push('- `redisCacheTtlSeconds`')
  lines.push('- `activityUpdateMode`')
  lines.push('- `processStaleSeconds`')
  lines.push('- `historyWindowMinutes`')
  lines.push('- `steamApiKey`')
  lines.push('- `autoAcceptNewDevices`')
  lines.push('- `inspirationAllowedDeviceHashes`')
  lines.push('- `pageLockEnabled`')
  lines.push('- `pageLockPassword`')
  lines.push('- `hcaptchaEnabled`')
  lines.push('- `hcaptchaSiteKey`')
  lines.push('- `hcaptchaSecretKey`')
  lines.push('')
  lines.push('## Success and Failure Rules')
  lines.push('')
  lines.push('Interpret responses strictly:')
  lines.push('')
  lines.push('- `200` with `success: true` means the action succeeded')
  lines.push('- `401` means missing or invalid credentials')
  lines.push('- `403` means the requested mode, field, or action is not allowed')
  lines.push('- `404` means the capability is not enabled')
  lines.push('- `503` means the server is not configured for that capability yet')
  lines.push('')
  lines.push('When a request fails:')
  lines.push('- Do not invent a workaround')
  lines.push('- Do not switch modes silently')
  lines.push('- Read the returned guide and show the user the real next step')
  lines.push('')
  lines.push('## Allowed Change Categories')
  lines.push('')
  lines.push('- Profile and branding')
  lines.push('- Theme and appearance')
  lines.push('- Content display text')
  lines.push('- Hitokoto configuration')
  lines.push('- Activity feed rules')
  lines.push('- Partial Steam settings')
  lines.push('')
  lines.push('## Configuration Field Rules')
  lines.push('')
  lines.push('Interpretation rules:')
  lines.push('- If a field is omitted in PATCH, keep the existing value')
  lines.push('- If a field is present, validate only that field and closely related dependent fields')
  lines.push('- Unless stated otherwise, string fields should be trimmed before sending')
  lines.push('- Array fields should contain only meaningful entries; remove empty strings before PATCH')
  lines.push('- For rule lists, send the full intended final list for that specific field')
  lines.push('')
  lines.push('### Profile and Identity')
  lines.push('')
  lines.push('- `pageTitle`: Browser title and main site title. Required, non-empty, length-limited')
  lines.push('- `userName`: Public display name. Required, non-empty')
  lines.push('- `userBio`: Public bio text. Required, non-empty')
  lines.push('- `avatarUrl`: Avatar image URL or data URL. Required, non-empty')
  lines.push('- `userNote`: Extra short note shown on profile area')
  lines.push('- `profileOnlineAccentColor`: Optional custom online accent color. Use `#RRGGBB` or empty/null to reset')
  lines.push('- `profileOnlinePulseEnabled`: Enables or disables the online dot pulse effect')
  lines.push('')
  lines.push('### Theme and Appearance')
  lines.push('')
  lines.push('- `themePreset`: Theme preset identifier. Use `customSurface` when editing custom theme surface fields')
  lines.push('- `themeCustomSurface`: Custom theme token object. Main fields are `background`, `bodyBackground`, `animatedBg`, `primary`, `foreground`, `card`, `border`, `mutedForeground`, `radius`, `hideFloatingOrbs`, `transparentAnimatedBg`')
  lines.push('- `customCss`: Extra sanitized custom CSS. Use only for targeted overrides, not for replacing the whole theme')
  lines.push('- `globalMouseTiltEnabled`: Enables desktop tilt motion effect')
  lines.push('- `globalMouseTiltGyroEnabled`: Enables gyro tilt on supported mobile devices')
  lines.push('- `hideActivityMedia`: Hides media payload from public activity cards without deleting stored records')
  lines.push('')
  lines.push('### AI Debugging Mode')
  lines.push('')
  lines.push('- `skillsDebugEnabled`: Master switch for AI debugging features. If not `true`, both Skills and MCP must be treated as unavailable')
  lines.push('- `aiToolMode`: User-selected active protocol. `skills` and `mcp` are mutually exclusive')
  lines.push('- `skillsAuthMode`: Current Skills authentication mode. Read-only for protocol selection; detect through `direct`')
  lines.push('- `mcpThemeToolsEnabled`: Extra MCP enable switch stored in site config. MCP is usable only when both `skillsDebugEnabled === true`, `aiToolMode === "mcp"`, and `mcpThemeToolsEnabled === true`')
  lines.push('')
  lines.push('### Home Text Labels')
  lines.push('')
  lines.push('- `currentlyText`: Title for the current status section')
  lines.push('- `earlierText`: Title for the earlier activity / inspiration section')
  lines.push('- `adminText`: Footer or admin entry label')
  lines.push('')
  lines.push('### Hitokoto Note')
  lines.push('')
  lines.push('- `userNoteHitokotoEnabled`: Enables random Hitokoto text for the note area')
  lines.push('- `userNoteHitokotoCategories`: Category list for Hitokoto source filtering')
  lines.push('- `userNoteHitokotoEncode`: Response format preference for Hitokoto service')
  lines.push('')
  lines.push('### Activity Filtering and Cute Message Rules')
  lines.push('')
  lines.push('- `appMessageRules`: Array of objects with `{ match, text }`. If `processName` includes `match`, the activity message becomes `text`')
  lines.push('- `appMessageRulesShowProcessName`: If `true`, append the real process name after a matched cute rule; if `false`, show only the custom text')
  lines.push('- `appFilterMode`: `blacklist` or `whitelist`')
  lines.push('- `appBlacklist`: Hidden process names when filter mode is `blacklist`')
  lines.push('- `appWhitelist`: Allowed process names when filter mode is `whitelist`; if empty under whitelist mode, no app activity is shown')
  lines.push('- `appNameOnlyList`: Process names that should show app name only and hide window title details')
  lines.push('- `captureReportedAppsEnabled`: Controls whether new reported apps are kept for history/rule suggestion/export')
  lines.push('- `mediaPlaySourceBlocklist`: Lowercased `metadata.play_source` list whose media metadata should be hidden from feed output')
  lines.push('')
  lines.push('### Schedule and Time')
  lines.push('')
  lines.push('- `displayTimezone`: Main timezone used for display formatting')
  lines.push('- `scheduleSlotMinutes`: Grid slot size; valid values are 15, 30, 45, 60')
  lines.push('- `schedulePeriodTemplate`: Array of teaching periods such as morning/afternoon/evening slots')
  lines.push('- `scheduleGridByWeekday`: Array of 7 weekday grid definitions')
  lines.push('- `scheduleCourses`: Array of course objects; period ids must stay consistent with `schedulePeriodTemplate`')
  lines.push('- `scheduleIcs`: Optional ICS text import payload, nullable')
  lines.push('- `scheduleInClassOnHome`: Enables the in-class banner on home')
  lines.push('- `scheduleHomeShowLocation`: Shows course location in home banner')
  lines.push('- `scheduleHomeShowTeacher`: Shows teacher in home banner')
  lines.push('- `scheduleHomeShowNextUpcoming`: Shows the next upcoming class on home')
  lines.push('- `scheduleHomeAfterClassesLabel`: Label shown after classes end')
  lines.push('')
  lines.push('### Steam and External Presence')
  lines.push('')
  lines.push('- `steamEnabled`: Enables Steam presence integration')
  lines.push('- `steamId`: Public Steam ID used for integration')
  lines.push('- `steamApiKey`: Restricted. Do not modify through Skills HTTP')
  lines.push('')
  lines.push('### Access Control and Safety')
  lines.push('')
  lines.push('- `pageLockEnabled`: Restricted. Page access lock switch')
  lines.push('- `pageLockPassword`: Restricted write input only; never send unless explicitly required in admin flow')
  lines.push('- `hcaptchaEnabled`: Restricted')
  lines.push('- `hcaptchaSiteKey`: Restricted')
  lines.push('- `hcaptchaSecretKey`: Restricted')
  lines.push('- `autoAcceptNewDevices`: Restricted')
  lines.push('- `inspirationAllowedDeviceHashes`: Restricted')
  lines.push('')
  lines.push('### Runtime and Storage Controls')
  lines.push('')
  lines.push('- `historyWindowMinutes`: Restricted in Skills HTTP')
  lines.push('- `processStaleSeconds`: Restricted in Skills HTTP')
  lines.push('- `activityUpdateMode`: Restricted in Skills HTTP')
  lines.push('- `useNoSqlAsCacheRedis`: Restricted in Skills HTTP')
  lines.push('- `redisCacheTtlSeconds`: Restricted in Skills HTTP')
  lines.push('- `activityRejectLockappSleep`: Controls rejection of lock-screen / sleep-like activity noise')
  lines.push('')
  lines.push('## MCP vs Skills Summary for New Agents')
  lines.push('')
  lines.push('- Skills = direct HTTP requests to `/api/llm/*`')
  lines.push('- MCP = connect a tool client to the MCP endpoint and call tools instead of raw HTTP CRUD')
  lines.push('- Use Skills when the client cannot mount MCP tools or when the server is in `skills` mode')
  lines.push('- Use MCP when the client supports MCP and the server is in `mcp` mode')
  lines.push('- Do not explain MCP as a different product area; it is only a different transport for the same site-management capability')
  lines.push('- If a new AI seems confused, restate the active mode using `direct` response rather than guessing from this document alone')
  lines.push('')
  lines.push('## Short Agent Checklist')
  lines.push('')
  lines.push('Before writing:')
  lines.push('- Read this document')
  lines.push('- Call `direct`')
  lines.push('- Confirm current usable mode')
  lines.push('- Gather only required credentials')
  lines.push('- Send only minimal PATCH fields')
  lines.push('')
  lines.push('If blocked:')
  lines.push('- Stop')
  lines.push('- Quote the server-provided next step in your own words')
  lines.push('- Ask the user to complete the missing authorization or configuration')

  return new NextResponse(lines.join('\n'), {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Cache-Control': 'no-store',
    },
  })
}
